# DCEConfig file
# Title: Donald Duck: Quack Attack
# EAN/IAN: 8023171000589
# MD5 (Donald.exe): 7A40DD5B97578429C62CC2D4D5768713
# DCEAPIHook version: v0.1.1
# Note: copy "Data\World\levels\LEVELS0.DAT" file from CD to the game dir


loader:
  target: "Donald.exe" 

virtual_drives: ['L']

hooks:
  - api: "GetDriveTypeA"
    arg1: "L:\\"
    return: 5 # DRIVE_CDROM
  - api: "GetVolumeInformationA"
    arg1: "L:\\"
    arg2: "DONALD"
    return: true

file_redirections:
  - source: "L:\\Data\\World\\levels\\LEVELS0.DAT"
    destination: ".\\Data\\World\\levels\\LEVELS0.DAT"