# DCEConfig file
# Title: Crazy Taxi
# EAN/IAN: 5017783555455
# MD5 (Crazy_Taxi_PC.exe): 630FCC1E5237733C729D7213B5C2687D
# DCEAPIHook version: v0.1.1

loader:
  target: "Crazy_Taxi_PC.exe" 

virtual_drives: ['L']

hooks:
  - api: "GetDriveTypeA"
    arg1: "L:\\"
    return: 5 # DRIVE_CDROM
  - api: "GetVolumeInformationA"
    arg1: "L:\\"
    arg2: "Crazy Taxi"
    return: true