# DCEConfig file
# Title: Carrera GRAND PRIX
# EAN/IAN: 4033841100444
# MD5 (Carrera.exe): A73AE41701CCA7F236F9A495EADF8CBC
# DCEAPIHook version: v0.5.0
# NOTE: Original disc is protected by phenoProtect

loader:
  target: "Carrera.exe" 

virtual_drives: ['F']

hooks:
  - api: "GetDriveTypeA"
    arg1: "F:\\"
    return: 5 # DRIVE_CDROM

file_redirections:
  - source: "F:\\resource.cfg"
    destination: ".\\resource.cfg" 
