# DCEConfig file
# Title: Tarzan (1999)
# EAN/IAN: 3546430017104
# MD5 (tarzan.exe): 23696342D35F0A61A7C94F4E1535134A
# DCEAPIHook version: v0.5.0
# Note: copy "DATA" directory from CD to the install dir

loader:
  target: "tarzan.exe" 

virtual_drives: ['L']

hooks:
  - api: "GetDriveTypeA"
    arg1: "L:\\"
    return: 5 # DRIVE_CDROM
  - api: "mciSendCommand"
    arg2: 0x803 #MCI_OPEN
    return: 0
  - api: "mciSendCommand"
    arg2: 0x814 #MCI_STATUS
    status_return: 1 # SUCCESS
    return: 0

directory_redirections:
  - source: "L:\\DATA\\"
    destination: ".\\DATA\\"